Removed strtolower because caused an error
With php72 on Redhat I used your script to search'n'replace strings in a mysql database. It caused 
Notice: Undefined index: Tables_in_databasename in /var/www/mysearchreplace/Class.MySQLSearchReplace.php on line 141
Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/mysearchreplace/Class.MySQLSearchReplace.php:144
so i had to fix this line and it worked perfect
Maybe others would have this issue?